### ISSUE TITLE
docker imgage to run v2r

### ISSUE THREAD

**Issue by Docop2** [pichi-router/pichi#5]
Hi
 So i found your project and it look bit more easier as to simply start a v2ray server and client. Or it's only a client ..  So basically, i'm quite not sure about the comand you put in the description. Do you have an example to do start a v2ray server ?  do i have to do an acme stuff or letencrypt to get the domain.com set before .. ?
thanks

**Comment by pichi-router** [comment]
Hi Docop2,
Thanks for your concern. VMESS protocol has not been supported yet, and it's going to be released in 1.5.0.
I was about to implement it in 1.4.0, but unfortunately VMESS protocol is too complicated, that i don't think it have to be.
That's why i didn't put any VMESS examples in README. So, please be patient or try other protocols.

About your last question, TLS/SSL certificate is mandatory if you want to use Trojan ingress. On the contrary, it's not necessary for VMESS. But, because of [a defect of VMESS protocol](https://github.com/v2ray/v2ray-core/issues/2523), it's usually used with TLS+Websocket. In that case, the certificate is necessary.

**Comment by Docop2** [comment]
thanks for.
