### ISSUE TITLE
pichi is great ！

### ISSUE THREAD

**Issue by imuzi** [pichi-router/pichi#6]
hi,there, pichi is just what i need for my app ... 
i'm facing some buid issues  for ios. Then truth is that the build detail is much less in README than the .azure folder .
can u pls complete README as .azrure  yml config did. 
i think this will help a lot for who want to build this for ios/android .

**Comment by imuzi** [comment]
https://dev.azure.com/pichi-ci/c0768972-b092-488b-94d7-3de76f38533f/_apis/build/builds/1028/logs/59
logs form azure helps a lot.

**Comment by imuzi** [comment]
BUILD SUCCEEDED, but when i am import into my xcode project, 100 errors shows up,`Undefined symbols for architecture arm64:
  "_mbedtls_sha512_finish_ret", referenced from:`, seams all error from lib mbedtls ,now  i am stuck here, rechecked all build details ,nothing different.
any help will be appreciate！！

**Comment by pichi-router** [comment]
Cross compiling is really much harder. The key point is building Boost for iOS, because the other dependencies and Pichi can easily build for iOS by using autoconf/CMake. So [deps-build/boost.sh](https://raw.githubusercontent.com/pichi-router/pichi/master/deps-build/boost.sh) might make sense. The steps might look like:
```
$ export PLATFORM=iOS ARCH=arm64 SYSROOT=/path/to/ios/sysroot
$ # Build baost
$ bash deps-build/boost.sh /path/to/boost/source
$ # Build others
$ # Build Pichi
$ cmake -G Xcode -D CMAKE_SYSTEM_NAME=${PLATFORM} -D CMAKE_OSX_DEPLOYMENT_TARGET=8.0 -D CMAKE_INSTALL_PREFIX=${SYSROOT} -B /path/to/build /path/to/pichi
$ cmake --build /path/to/build --config Release -- -sdk iphoneos
```
Frankly speaking, it is still complicated. Some wonderful tools might be supported for cross compiling, such as [Conan](https://conan.io/). That’s why I didn’t describe cross compiling in detail.

**Comment by imuzi** [comment]
Thank u for replying me! I‘ve succeed embed pichi into all my native project(android|iOS|win|mac). thank u very much ,i could not finish my work without pichi . Those who want build for cross compiling, just look at the .azure folder, u will find the build detail with build log and the .yml file.Thank u again! Best wishes~
